2022-11-07 15:48:50,537 ERROR: Exception on /index [GET] [in C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Jai\Desktop\Project Management Y2 (2022-23) - Assignment\ProjectManagementY2-2223\app\main\routes.py", line 9, in index
    return render_template('index.html',  title='Home')
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jai\Desktop\Project Management Y2 (2022-23) - Assignment\ProjectManagementY2-2223\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Jai\Desktop\Project Management Y2 (2022-23) - Assignment\ProjectManagementY2-2223\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "C:\Users\Jai\Desktop\Project Management Y2 (2022-23) - Assignment\ProjectManagementY2-2223\app\templates\base.html", line 33, in block 'navbar'
    <li><a href="/logout" >Logout</a></li>
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'auth' is undefined
2022-11-08 13:59:21,689 INFO: Template - Name startup [in C:\Users\fayee\OneDrive\Desktop\Applied Computing Year 2\Project Management and Development\Assignment\ProjectManagementY2-2223\app\__init__.py:71]
2022-11-08 14:01:01,494 INFO: Template - Name startup [in C:\Users\fayee\OneDrive\Desktop\Applied Computing Year 2\Project Management and Development\Assignment\ProjectManagementY2-2223\app\__init__.py:71]
